import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Container } from "@/shared/components/layout/container";

const hero = "https://lh3.googleusercontent.com/aida-public/AB6AXuAx1EYaB9Blh965Nub9RDokUeqX6dIW3zuusAKDcWEaZwtlK2mZC18YCzYeKF9a-Djz_ft7lsqcXZwhx2VhRwJKAVrSy_sFvB4jp3SUDvQlUCv6MnrH9K1Mc4ABDVTjfK_MJ1a-LfuwRS7yAUAIDk2FRw0xGyGjMeLqKzHh_9FXLAjGR4CmiytIgLLt-fQ2C_3E7DMFWc8ufz2Bop1AckIX-lgdkfKoXK-AITeYCIk8C7ym7G_Ey1TI";

export default function LandingPage() {
  const paths = ["/login", "/mercado", "/login", "/artesana/mi-historia"];
  const ways = [["APRENDER", "Cursos y herramientas digitales"], ["EMPRENDER", "Vitrina cultural con dignidad"], ["COLABORAR", "Comunidad y acompanamiento"], ["COMPARTIR", "Historias que preservan saberes"]];
  return <main className="bg-white text-[#123f78]"><section className="relative min-h-[390px] bg-cover bg-center" style={{ backgroundImage: `linear-gradient(rgba(245,247,246,.72),rgba(245,247,246,.72)),url(${hero})` }}><Container className="flex min-h-[390px] items-center justify-center text-center"><div><p className="font-serif text-3xl text-[#b5245b]">Warmi</p><h1 className="mt-2 font-serif text-5xl font-bold tracking-[.1em] md:text-7xl">WARMI DIGITAL</h1><p className="mt-3 text-xl italic text-[#c22b61]">Artesanas conectadas, historias que transforman.</p></div></Container></section><nav className="grid grid-cols-2 font-ui text-label-ui text-white md:grid-cols-4"><Link className="bg-[#5576a7] px-6 py-7 text-center" href="#programa">PROGRAMA WARMI</Link><Link className="bg-[#ea9b62] px-6 py-7 text-center" href="#descubre">DESCUBRE</Link><Link className="bg-[#55d2dd] px-6 py-7 text-center" href="#identidad">IDENTIDAD WARMI</Link><Link className="bg-[#f0bf35] px-6 py-7 text-center" href="/login">UNETE A WARMI</Link></nav><section id="programa"><Container className="py-14"><h2 className="border-t-4 border-[#123f78] pt-8 font-serif text-4xl uppercase md:text-5xl">Sllapan wawqaykunaman allin hamuy</h2><p className="mt-6 max-w-2xl text-body-lg">Warmi une aprendizaje digital, acompanamiento humano y preservacion cultural para fortalecer los caminos de cada artesana.</p><p className="mt-7 inline-block bg-[#d497b1] px-5 py-4 font-ui text-label-ui text-white">BIENVENIDAS A WARMI</p></Container></section><section id="identidad" className="border-y-4 border-[#55d2dd] bg-[#ecfcfd]"><Container className="grid gap-8 py-14 md:grid-cols-3"><div><p className="font-ui text-label-ui">IDENTIDAD WARMI</p><h2 className="mt-3 font-serif text-headline-lg">Nuestra fuerza nace de la comunidad.</h2></div><p className="text-body-lg">Cada tecnica, historia y pieza pertenece a una artesana y a su territorio. La tecnologia ayuda a documentar y compartir ese legado con respeto.</p><Link className="self-center bg-[#55d2dd] px-6 py-4 text-center font-ui text-label-ui" href="/mercado">Conocer historias y piezas</Link></Container></section><section id="descubre" className="bg-[#f7f3ef]"><Container className="py-16"><p className="text-center font-serif text-2xl italic text-[#c22b61]">Un programa con mujeres artesanas para mujeres artesanas</p><h2 className="mt-10 font-serif text-5xl uppercase tracking-[.2em]">Descubre</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{ways.map(([title, text], i) => <Link key={title} href={paths[i]} className="border-b-8 border-[#f0bf35] bg-white p-6 transition-transform hover:-translate-y-1"><p className="font-ui text-label-ui text-[#c22b61]">{title}</p><p className="mt-3 font-serif text-headline-md">{text}</p><ArrowRight className="mt-6 h-5 w-5 text-[#fc6b22]" /></Link>)}</div></Container></section></main>;
}
